version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: Contenedor1  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "Tienda"
      MYSQL_USER: "usuario"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3307:3306"
    volumes:
      - "C:/Users/luisa/Desktop/DockerCompose/mysql_data:/var/lib/mysql"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
